<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\syncronizationdemo]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[syncronizationdemo]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:06]]></Time>
<TimeTick>1678709586</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OK.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, 10000]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:06]]></Time>
<TimeTick>1678709586</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" status="Warning" Source="Action1" SourceLine="2" >
<Disp><![CDATA[OK.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:19]]></Time>
<TimeTick>1678709599</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="24" Source="Action1" SourceLine="4" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="21" status="Warning" Source="Action1" SourceLine="2" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[democalculator for testing]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:46]]></Time>
<TimeTick>1678709626</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[democalculator for testing.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:46]]></Time>
<TimeTick>1678709626</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="Action1" SourceLine="11" >
<Disp><![CDATA[democalculator for testing.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Ideal Weight Calculator]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:47]]></Time>
<TimeTick>1678709627</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[cage.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["22"]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:47]]></Time>
<TimeTick>1678709627</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1" SourceLine="12" >
<Disp><![CDATA[cage.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[csex.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["f"]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:47]]></Time>
<TimeTick>1678709627</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="Action1" SourceLine="13" >
<Disp><![CDATA[csex.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[cheightinch.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["00"]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:48]]></Time>
<TimeTick>1678709628</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Action1" SourceLine="14" >
<Disp><![CDATA[cheightinch.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Calculate.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:48]]></Time>
<TimeTick>1678709628</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="40" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Calculate.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Metric Units.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:53]]></Time>
<TimeTick>1678709633</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="43" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Metric Units.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[cheightmeter.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["170"]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:54]]></Time>
<TimeTick>1678709634</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Action1" SourceLine="17" >
<Disp><![CDATA[cheightmeter.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Calculate.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:43:58]]></Time>
<TimeTick>1678709638</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Calculate.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Calculate.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:44:01]]></Time>
<TimeTick>1678709641</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" Source="Action1" SourceLine="19" >
<Disp><![CDATA[Calculate.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Other Units.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 17:44:05]]></Time>
<TimeTick>1678709645</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="55" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Other Units.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[13-03-2023 - 17:44:06]]></Time>
<TimeTick>1678709646</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Frame"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (4 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>name=<br>micclass=Frame<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (4 objects found)&nbsp;</FONT></u><br>
micclass=Frame<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=<SPAN class=passed> (Used</SPAN>, 4 matches)</SPAN><br>title=Quick Converters: Calculator.net<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>url=https://www.calculator.net/converter/converter.php?type=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-03-2023 - 17:44:06]]></Time>
<TimeTick>1678709646</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="59" Source="Action1" SourceLine="21" >
<Disp><![CDATA["Frame"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[calFrom.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Millimeter"]]></Details>
<Time><![CDATA[13-03-2023 - 17:44:06]]></Time>
<TimeTick>1678709646</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="60" Source="Action1" SourceLine="21" >
<Disp><![CDATA[calFrom.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="58" Source="Action1" SourceLine="21" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="30" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Ideal Weight Calculator]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" Source="Action1" SourceLine="11" >
<Disp><![CDATA[democalculator for testing]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 17:41:44" eTime="13-03-2023 - 17:44:06" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[syncronizationdemo Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-03-2023 - 17:41:39" eTime="13-03-2023 - 17:44:07" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test syncronizationdemo Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>