<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\lab 13]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[lab 13]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:29]]></Time>
<TimeTick>1678692269</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:29]]></Time>
<TimeTick>1678692269</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["anu"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pass234"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="10" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="11" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:33]]></Time>
<TimeTick>1678692273</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:34]]></Time>
<TimeTick>1678692274</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:34]]></Time>
<TimeTick>1678692274</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["kannan"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:36]]></Time>
<TimeTick>1678692276</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pass678"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:36]]></Time>
<TimeTick>1678692276</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" Source="Action1" SourceLine="10" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:36]]></Time>
<TimeTick>1678692276</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" Source="Action1" SourceLine="11" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:36]]></Time>
<TimeTick>1678692276</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:37]]></Time>
<TimeTick>1678692277</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:37]]></Time>
<TimeTick>1678692277</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="44" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["vaani"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:39]]></Time>
<TimeTick>1678692279</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pass123"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:39]]></Time>
<TimeTick>1678692279</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" Source="Action1" SourceLine="10" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:39]]></Time>
<TimeTick>1678692279</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="Action1" SourceLine="11" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:39]]></Time>
<TimeTick>1678692279</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:40]]></Time>
<TimeTick>1678692280</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:40]]></Time>
<TimeTick>1678692280</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="60" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["devi"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:42]]></Time>
<TimeTick>1678692282</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pass000"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:42]]></Time>
<TimeTick>1678692282</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="Action1" SourceLine="10" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:42]]></Time>
<TimeTick>1678692282</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" Source="Action1" SourceLine="11" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:42]]></Time>
<TimeTick>1678692282</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:43]]></Time>
<TimeTick>1678692283</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:43]]></Time>
<TimeTick>1678692283</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="76" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["student"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:44]]></Time>
<TimeTick>1678692284</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Password123"]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:44]]></Time>
<TimeTick>1678692284</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" Source="Action1" SourceLine="10" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:44]]></Time>
<TimeTick>1678692284</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" Source="Action1" SourceLine="11" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:45]]></Time>
<TimeTick>1678692285</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="89" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" status="Passed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Passed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:54:28" eTime="13-03-2023 - 12:54:45" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[lab 13 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T37" iterID="2" >
<Action rID="T38">
<AName><![CDATA[Action1]]></AName>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:46]]></Time>
<TimeTick>1678692286</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:54:46]]></Time>
<TimeTick>1678692286</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="97" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="96" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[username]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"username"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[username]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //INPUT[@id="username"]<br>|rows = 0<br>placeholder = <br>Name = username<br>Max Length = 524288<br>Html Id = username<br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="133" status="Warning" nType="Description" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="132" status="Failed" nType="Run Error" Source="Action1" SourceLine="8" >
<Disp><![CDATA[username]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="131" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="130" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:07]]></Time>
<TimeTick>1678692307</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;username&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (9): &quot;Browser(&quot;Test Login | Practice&quot;).Page(&quot;Test Login | Practice&quot;).WebEdit(&quot;username&quot;).Set DataTable(&quot;username&quot;, dtlocalSheet)&quot;. ]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:08]]></Time>
<TimeTick>1678692308</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="136" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[13-03-2023 - 12:55:16]]></Time>
<TimeTick>1678692316</TimeTick>
<NodeArgs eType="General" icon="11" nRep="137" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="135" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="134" status="Failed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:54:45" eTime="13-03-2023 - 12:55:16" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="93" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="92" status="Failed" >
<Disp><![CDATA[lab 13 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-03-2023 - 12:54:24" eTime="13-03-2023 - 12:55:16" passed="6" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test lab 13 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>